### ISSUE TITLE
Going to other users' profiles changes the login name

### ISSUE THREAD

**Issue by AustinKellar** [Sidney-/slugtrade#46]
When you click on someone else's profile via the /users endpoint, the name on the welcome message has that person's name on it rather than the name of the logged in user.

**Comment by egomish** [comment]
How to replicate:
- ensure you are not logged in
- view endpoint "profile/1/" and see that the header says "Welcome, admin!"
- view endpoint "profile/2/" and see that the header says "Welcome, Test!"

**Comment by egomish** [comment]
Fixed in commit ab745b0f01ae107c8f012e852502ec5d1b5d57c0.
